name: Build/Push PyUrlViewer

on:
  push:
    paths:
      - 'PyUrlViewer/**'
  pull_request:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image [true|false]'
        required: false
        default: 'false'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Publish image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: PyUrlViewer/
        push: ${{ github.event_name != 'pull_request' || github.event.inputs.push == 'true' }}
        tags: ghcr.io/tigattack/pyurlviewer:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
